"""Live sessions: the browser, who may drive it, and how to sign in."""

from cua.session.auth import (
    MEMBER_CONSOLE,
    AuthError,
    AuthFailed,
    AuthLocked,
    AuthProfile,
    AuthResult,
    AuthUnavailable,
    Credentials,
    authenticate,
    is_authenticated,
)
from cua.session.human import HumanAction, HumanWatcher, Watchable
from cua.session.intervention import (
    ABORTED,
    EXPIRED,
    GRANTED,
    OPEN,
    RESOLVED,
    UNVERIFIED,
    Handoff,
    Intervention,
    InterventionRegistry,
    InterventionRequest,
    hand_back,
    handoff_timeout,
    take_control,
)
from cua.session.manager import (
    GuardedSurface,
    Session,
    SessionManager,
    StateChange,
)
from cua.session.state import (
    CONTROL_BY_STATE,
    LEGAL_TRANSITIONS,
    ControlViolation,
    IllegalTransition,
    can_transition,
    control_for,
    is_terminal,
)

__all__ = [
    "ABORTED",
    "authenticate",
    "AuthError",
    "AuthFailed",
    "AuthLocked",
    "AuthProfile",
    "AuthResult",
    "AuthUnavailable",
    "can_transition",
    "CONTROL_BY_STATE",
    "control_for",
    "ControlViolation",
    "Credentials",
    "EXPIRED",
    "GRANTED",
    "GuardedSurface",
    "hand_back",
    "Handoff",
    "handoff_timeout",
    "HumanAction",
    "HumanWatcher",
    "IllegalTransition",
    "Intervention",
    "InterventionRegistry",
    "InterventionRequest",
    "is_authenticated",
    "is_terminal",
    "LEGAL_TRANSITIONS",
    "MEMBER_CONSOLE",
    "OPEN",
    "RESOLVED",
    "Session",
    "SessionManager",
    "StateChange",
    "take_control",
    "UNVERIFIED",
    "Watchable",
]
